name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: imransetiadi
          filename: github-metrics.svg
          committer_token: ${{ secrets.METRICS_TOKEN }}

          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_lines: yes

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
